### ISSUE TITLE
Provide guidelines to setup and running this project

### ISSUE THREAD

**Issue by rasp20** [elitedev201/React-Dating-app#1]
Hi team @yann120 @Segolene-Alquier.  Could you provide guidelines to setup and running this project? I interest with this project. Thanks

**Comment by yann120** [comment]
Hey @rasp20, thanks for your interest of our project :) 
This was a student project that we made 2 years ago for our school Ecole 42.
I'm not sure this project is still working because of the dependencies and is not maintained.
I will not have time to write guidelines, but I think you just have to run the server. Maybe `npm start` should do the trick 😃
